
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: unsaved
* name: Font1
* family: Arial
* size: 8
* style: Bold
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Grayscale 4
* data block size: 16 bit(s), uint16_t
* RLE compression enabled: no
* conversion type: Grayscale, not_used not_used
* split to rows: yes
* bits per pixel: 4
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint16_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>
#include "fonts.h"


#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x20[10] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x20 = { image_data_Font1_0x20,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x21[10] = {
    // ∙
    // ∙
    // █
    // █
    // █
    // █
    // █
    // █
    // ∙
    // ∙
    0x0000, 
    0x0000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x21 = { image_data_Font1_0x21,
    1, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x22[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // █∙█∙
    // █∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0xf0f0, 
    0xf0f0, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x22 = { image_data_Font1_0x22,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x23[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙█∙█
    // ∙█∙█
    // ████
    // █∙█∙
    // ████
    // █∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0f0f, 
    0x0f0f, 
    0xffff, 
    0xf0f0, 
    0xffff, 
    0xf0f0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x23 = { image_data_Font1_0x23,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x24[10] = {
    // ∙∙∙∙
    // ∙█∙∙
    // ███∙
    // ███∙
    // ██∙∙
    // ∙██∙
    // ███∙
    // ███∙
    // ∙█∙∙
    // ∙∙∙∙
    0x0000, 
    0x0f00, 
    0xfff0, 
    0xfff0, 
    0xff00, 
    0x0ff0, 
    0xfff0, 
    0xfff0, 
    0x0f00, 
    0x0000
};
static const tImage Font1_0x24 = { image_data_Font1_0x24,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x25[20] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ███∙█∙∙∙
    // █∙█∙█∙∙∙
    // ████∙∙∙∙
    // ∙∙∙████∙
    // ∙∙█∙█∙█∙
    // ∙∙█∙███∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xfff0, 0xf000, 
    0xf0f0, 0xf000, 
    0xffff, 0x0000, 
    0x000f, 0xfff0, 
    0x00f0, 0xf0f0, 
    0x00f0, 0xfff0, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x25 = { image_data_Font1_0x25,
    8, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x26[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ████∙∙
    // █∙∙█∙∙
    // ∙██∙∙∙
    // ███∙█∙
    // █∙∙██∙
    // ∙█████
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xffff, 0x0000, 
    0xf00f, 0x0000, 
    0x0ff0, 0x0000, 
    0xfff0, 0xf000, 
    0xf00f, 0xf000, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x26 = { image_data_Font1_0x26,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x27[10] = {
    // ∙∙
    // ∙∙
    // █∙
    // █∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    0x0000, 
    0x0000, 
    0xf000, 
    0xf000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x27 = { image_data_Font1_0x27,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x28[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // █∙∙
    // █∙∙
    // █∙∙
    // █∙∙
    // █∙∙
    // █∙∙
    // ∙█∙
    0x0000, 
    0x0000, 
    0x0f00, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0x0f00
};
static const tImage Font1_0x28 = { image_data_Font1_0x28,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x29[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙█
    // ∙∙█
    // ∙∙█
    // ∙∙█
    // ∙∙█
    // ∙∙█
    // ∙█∙
    0x0000, 
    0x0000, 
    0x0f00, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0f00
};
static const tImage Font1_0x29 = { image_data_Font1_0x29,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x2a[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ███
    // █∙█
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0x0f00, 
    0xfff0, 
    0xf0f0, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x2a = { image_data_Font1_0x2a,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x2b[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙█∙∙∙
    // ███∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0x0000, 
    0xfff0, 0x0000, 
    0x0f00, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x2b = { image_data_Font1_0x2b,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x2c[10] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // █∙
    // █∙
    // ∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0xf000, 
    0xf000, 
    0x0000
};
static const tImage Font1_0x2c = { image_data_Font1_0x2c,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x2d[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ███
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0xfff0, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x2d = { image_data_Font1_0x2d,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x2e[10] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // █∙
    // ∙∙
    // ∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0xf000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x2e = { image_data_Font1_0x2e,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x2f[10] = {
    // ∙∙
    // ∙∙
    // ∙█
    // ∙█
    // ∙█
    // █∙
    // █∙
    // █∙
    // ∙∙
    // ∙∙
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0xf000, 
    0xf000, 
    0xf000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x2f = { image_data_Font1_0x2f,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x30[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙█∙∙
    // █∙█∙
    // █∙█∙
    // █∙█∙
    // █∙█∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0f00, 
    0xf0f0, 
    0xf0f0, 
    0xf0f0, 
    0xf0f0, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x30 = { image_data_Font1_0x30,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x31[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙██∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x00f0, 
    0x0ff0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x31 = { image_data_Font1_0x31,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x32[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ███∙
    // █∙█∙
    // ∙∙█∙
    // ∙██∙
    // ██∙∙
    // ███∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0xfff0, 
    0xf0f0, 
    0x00f0, 
    0x0ff0, 
    0xff00, 
    0xfff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x32 = { image_data_Font1_0x32,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x33[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ███∙
    // █∙█∙
    // ∙█∙∙
    // ∙∙█∙
    // █∙█∙
    // ██∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0xfff0, 
    0xf0f0, 
    0x0f00, 
    0x00f0, 
    0xf0f0, 
    0xff00, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x33 = { image_data_Font1_0x33,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x34[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙██∙
    // ∙██∙
    // █∙█∙
    // ████
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x00f0, 
    0x0ff0, 
    0x0ff0, 
    0xf0f0, 
    0xffff, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x34 = { image_data_Font1_0x34,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x35[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙██∙
    // ██∙∙
    // ███∙
    // ∙∙█∙
    // █∙█∙
    // ███∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0ff0, 
    0xff00, 
    0xfff0, 
    0x00f0, 
    0xf0f0, 
    0xfff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x35 = { image_data_Font1_0x35,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x36[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙██∙
    // █∙█∙
    // █∙∙∙
    // ███∙
    // █∙█∙
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0ff0, 
    0xf0f0, 
    0xf000, 
    0xfff0, 
    0xf0f0, 
    0x0ff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x36 = { image_data_Font1_0x36,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x37[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ███∙
    // ∙██∙
    // ∙█∙∙
    // █∙∙∙
    // █∙∙∙
    // █∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0xfff0, 
    0x0ff0, 
    0x0f00, 
    0xf000, 
    0xf000, 
    0xf000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x37 = { image_data_Font1_0x37,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x38[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ███∙
    // █∙█∙
    // ∙█∙∙
    // █∙█∙
    // █∙█∙
    // ███∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0xfff0, 
    0xf0f0, 
    0x0f00, 
    0xf0f0, 
    0xf0f0, 
    0xfff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x38 = { image_data_Font1_0x38,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x39[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ██∙∙
    // █∙█∙
    // ███∙
    // ∙∙█∙
    // █∙█∙
    // ██∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0xff00, 
    0xf0f0, 
    0xfff0, 
    0x00f0, 
    0xf0f0, 
    0xff00, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x39 = { image_data_Font1_0x39,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x3a[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x3a = { image_data_Font1_0x3a,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x3b[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0000
};
static const tImage Font1_0x3b = { image_data_Font1_0x3b,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x3c[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙█∙
    // ███∙∙
    // ███∙∙
    // ∙∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x000f, 0x0000, 
    0xfff0, 0x0000, 
    0xfff0, 0x0000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x3c = { image_data_Font1_0x3c,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x3d[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xffff, 0x0000, 
    0x0000, 0x0000, 
    0xffff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x3d = { image_data_Font1_0x3d,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x3e[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙∙∙
    // ∙███∙
    // ∙███∙
    // █∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xf000, 0x0000, 
    0x0fff, 0x0000, 
    0x0fff, 0x0000, 
    0xf000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x3e = { image_data_Font1_0x3e,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x3f[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // ∙∙∙█∙
    // ∙██∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0ff0, 0x0000, 
    0xf00f, 0x0000, 
    0x000f, 0x0000, 
    0x0ff0, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x3f = { image_data_Font1_0x3f,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x40[20] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙█████∙
    // ∙███████
    // ███∙∙█∙█
    // ██∙∙∙█∙█
    // ██∙∙██∙█
    // █∙█████∙
    // ∙█∙∙∙∙∙█
    // ∙∙█████∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0xfff0, 
    0x0fff, 0xffff, 
    0xfff0, 0x0f0f, 
    0xff00, 0x0f0f, 
    0xff00, 0xff0f, 
    0xf0ff, 0xfff0, 
    0x0f00, 0x000f, 
    0x00ff, 0xfff0
};
static const tImage Font1_0x40 = { image_data_Font1_0x40,
    8, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x41[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // █████
    // █∙∙∙█
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00f0, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0xffff, 0xf000, 
    0xf000, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x41 = { image_data_Font1_0x41,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x42[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█████
    // ∙█∙∙∙█
    // ∙████∙
    // ∙█∙∙∙█
    // ∙█∙∙∙█
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xff00, 
    0x0f00, 0x0f00, 
    0x0fff, 0xf000, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x42 = { image_data_Font1_0x42,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x43[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ██∙∙∙█
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ██∙∙∙█
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0xff00, 0x0f00, 
    0xf000, 0x0000, 
    0xf000, 0x0000, 
    0xff00, 0x0f00, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x43 = { image_data_Font1_0x43,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x44[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙█∙∙∙█
    // ∙█∙∙∙█
    // ∙█∙∙∙█
    // ∙█∙∙∙█
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x44 = { image_data_Font1_0x44,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x45[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙████
    // ∙█∙∙∙
    // ∙████
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙████
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x45 = { image_data_Font1_0x45,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x46[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙████
    // ∙█∙∙∙
    // ∙████
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x46 = { image_data_Font1_0x46,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x47[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙∙∙
    // █∙∙██∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0x0000, 
    0xf000, 0xf000, 
    0xf000, 0x0000, 
    0xf00f, 0xf000, 
    0xf000, 0xf000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x47 = { image_data_Font1_0x47,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x48[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙████∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x48 = { image_data_Font1_0x48,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x49[10] = {
    // ∙∙
    // ∙∙
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙∙
    // ∙∙
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x49 = { image_data_Font1_0x49,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x4a[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // █∙█∙
    // ███∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0xf0f0, 
    0xfff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x4a = { image_data_Font1_0x4a,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x4b[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙█∙
    // ∙█∙█∙∙
    // ∙██∙∙∙
    // ∙███∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0xf000, 
    0x0f0f, 0x0000, 
    0x0ff0, 0x0000, 
    0x0fff, 0x0000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x4b = { image_data_Font1_0x4b,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x4c[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x4c = { image_data_Font1_0x4c,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x4d[20] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙██∙██∙
    // ∙██∙██∙
    // ∙██∙██∙
    // ∙██∙██∙
    // ∙█∙█∙█∙
    // ∙█∙█∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0ff0, 0xff00, 
    0x0ff0, 0xff00, 
    0x0ff0, 0xff00, 
    0x0ff0, 0xff00, 
    0x0f0f, 0x0f00, 
    0x0f0f, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x4d = { image_data_Font1_0x4d,
    7, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x4e[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙█∙
    // ∙██∙█∙
    // ∙██∙█∙
    // ∙█∙██∙
    // ∙█∙██∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0xf000, 
    0x0ff0, 0xf000, 
    0x0ff0, 0xf000, 
    0x0f0f, 0xf000, 
    0x0f0f, 0xf000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x4e = { image_data_Font1_0x4e,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x4f[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ██∙∙██
    // █∙∙∙∙█
    // █∙∙∙∙█
    // ██∙∙██
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0xff00, 0xff00, 
    0xf000, 0x0f00, 
    0xf000, 0x0f00, 
    0xff00, 0xff00, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x4f = { image_data_Font1_0x4f,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x50[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙████
    // ∙█∙∙█
    // ∙█∙∙█
    // ∙███∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x50 = { image_data_Font1_0x50,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x51[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ██∙∙∙█
    // █∙∙∙∙█
    // █∙∙█∙█
    // ██∙██∙
    // ∙█████
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0xff00, 0x0f00, 
    0xf000, 0x0f00, 
    0xf00f, 0x0f00, 
    0xff0f, 0xf000, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x51 = { image_data_Font1_0x51,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x52[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙█∙∙█∙
    // ∙████∙
    // ∙█∙█∙∙
    // ∙█∙█∙∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0xf000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x52 = { image_data_Font1_0x52,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x53[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙███∙
    // ∙█∙█∙
    // ∙██∙∙
    // ∙∙██∙
    // ∙█∙█∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0ff0, 0x0000, 
    0x00ff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x53 = { image_data_Font1_0x53,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x54[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █████
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xffff, 0xf000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x54 = { image_data_Font1_0x54,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x55[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙██∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x55 = { image_data_Font1_0x55,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x56[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙∙█
    // █∙∙∙█
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xf000, 0xf000, 
    0xf000, 0xf000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x00f0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x56 = { image_data_Font1_0x56,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x57[30] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // █∙∙∙█∙∙∙█
    // ∙∙∙███∙∙∙
    // ∙█∙█∙█∙█∙
    // ∙█∙█∙█∙█∙
    // ∙∙∙█∙█∙∙∙
    // ∙∙█∙∙∙█∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0xf000, 0xf000, 0xf000, 
    0x000f, 0xff00, 0x0000, 
    0x0f0f, 0x0f0f, 0x0000, 
    0x0f0f, 0x0f0f, 0x0000, 
    0x000f, 0x0f00, 0x0000, 
    0x00f0, 0x00f0, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Font1_0x57 = { image_data_Font1_0x57,
    9, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x58[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x58 = { image_data_Font1_0x58,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x59[20] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // █∙∙∙█∙
    // ∙█∙█∙∙
    // ∙█∙█∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xf000, 0xf000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x59 = { image_data_Font1_0x59,
    6, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x5a[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █████
    // ∙∙∙██
    // ∙∙██∙
    // ∙██∙∙
    // ██∙∙∙
    // █████
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xffff, 0xf000, 
    0x000f, 0xf000, 
    0x00ff, 0x0000, 
    0x0ff0, 0x0000, 
    0xff00, 0x0000, 
    0xffff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x5a = { image_data_Font1_0x5a,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x5b[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙██
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙██
    0x0000, 
    0x0000, 
    0x0ff0, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0ff0
};
static const tImage Font1_0x5b = { image_data_Font1_0x5b,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x5c[10] = {
    // ∙∙
    // ∙∙
    // █∙
    // █∙
    // █∙
    // ∙█
    // ∙█
    // ∙█
    // ∙∙
    // ∙∙
    0x0000, 
    0x0000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x5c = { image_data_Font1_0x5c,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x5d[10] = {
    // ∙∙∙
    // ∙∙∙
    // ██∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ██∙
    0x0000, 
    0x0000, 
    0xff00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0xff00
};
static const tImage Font1_0x5d = { image_data_Font1_0x5d,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x5e[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙██∙∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0ff0, 0x0000, 
    0x0ff0, 0x0000, 
    0xf00f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x5e = { image_data_Font1_0x5e,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x5f[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ████
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0xffff
};
static const tImage Font1_0x5f = { image_data_Font1_0x5f,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x60[10] = {
    // ∙∙∙
    // ∙∙∙
    // ██∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0xff00, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x60 = { image_data_Font1_0x60,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x61[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ███∙
    // █∙█∙
    // ∙██∙
    // █∙█∙
    // ███∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0xfff0, 
    0xf0f0, 
    0x0ff0, 
    0xf0f0, 
    0xfff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x61 = { image_data_Font1_0x61,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x62[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xf000, 0x0000, 
    0xfff0, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xfff0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x62 = { image_data_Font1_0x62,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x63[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙██∙
    // █∙█∙
    // █∙∙∙
    // █∙█∙
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0ff0, 
    0xf0f0, 
    0xf000, 
    0xf0f0, 
    0x0ff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x63 = { image_data_Font1_0x63,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x64[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙█∙
    // ∙███∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x000f, 0x0000, 
    0x0fff, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x64 = { image_data_Font1_0x64,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x65[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙█∙∙
    // █∙█∙
    // ███∙
    // █∙█∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0xf0f0, 
    0xfff0, 
    0xf0f0, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x65 = { image_data_Font1_0x65,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x66[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙██
    // ███
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0x0ff0, 
    0xfff0, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x66 = { image_data_Font1_0x66,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x67[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙███∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // █∙∙█∙
    // ████∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0x0fff, 0x0000, 
    0xf00f, 0x0000, 
    0xffff, 0x0000
};
static const tImage Font1_0x67 = { image_data_Font1_0x67,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x68[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙∙∙
    // █∙██∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xf000, 0x0000, 
    0xf0ff, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x68 = { image_data_Font1_0x68,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x69[10] = {
    // ∙∙
    // ∙∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // ∙∙
    // ∙∙
    0x0000, 
    0x0000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x69 = { image_data_Font1_0x69,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x6a[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ██∙
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0xff00
};
static const tImage Font1_0x6a = { image_data_Font1_0x6a,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x6b[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // █∙∙∙
    // █∙█∙
    // ███∙
    // ███∙
    // █∙█∙
    // █∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0xf000, 
    0xf0f0, 
    0xfff0, 
    0xfff0, 
    0xf0f0, 
    0xf0f0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x6b = { image_data_Font1_0x6b,
    4, 10, 16};
#endif

#if (0x069 == 0x0)
static const uint16_t image_data_Font1_0x6c[10] = {
    // ∙∙
    // ∙∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // ∙∙
    // ∙∙
    0x0000, 
    0x0000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x6c = { image_data_Font1_0x6c,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x6d[20] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // █████∙∙
    // █∙█∙█∙∙
    // █∙█∙█∙∙
    // █∙█∙█∙∙
    // █∙█∙█∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xffff, 0xf000, 
    0xf0f0, 0xf000, 
    0xf0f0, 0xf000, 
    0xf0f0, 0xf000, 
    0xf0f0, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x6d = { image_data_Font1_0x6d,
    7, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x6e[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ████∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xffff, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x6e = { image_data_Font1_0x6e,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x6f[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0ff0, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0x0ff0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x6f = { image_data_Font1_0x6f,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x70[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xfff0, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xfff0, 0x0000, 
    0xf000, 0x0000, 
    0xf000, 0x0000
};
static const tImage Font1_0x70 = { image_data_Font1_0x70,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x71[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙███∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0x0fff, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000
};
static const tImage Font1_0x71 = { image_data_Font1_0x71,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x72[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ███
    // █∙∙
    // █∙∙
    // █∙∙
    // █∙∙
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0xfff0, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x72 = { image_data_Font1_0x72,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x73[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x73 = { image_data_Font1_0x73,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x74[10] = {
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ███
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙██
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0f00, 
    0x0f00, 
    0xfff0, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0ff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x74 = { image_data_Font1_0x74,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x75[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xf00f, 0x0000, 
    0xffff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x75 = { image_data_Font1_0x75,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x76[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x76 = { image_data_Font1_0x76,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x77[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙█∙█
    // █∙█∙█
    // █∙∙∙█
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xf0f0, 0xf000, 
    0xf0f0, 0xf000, 
    0xf000, 0xf000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x77 = { image_data_Font1_0x77,
    5, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x78[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙██∙
    // ∙██∙
    // ∙█∙∙
    // ∙██∙
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0ff0, 
    0x0ff0, 
    0x0f00, 
    0x0ff0, 
    0x0ff0, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x78 = { image_data_Font1_0x78,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x79[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // █∙█
    // █∙█
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // █∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0xf0f0, 
    0xf0f0, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0xf000
};
static const tImage Font1_0x79 = { image_data_Font1_0x79,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x7a[10] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙███
    // ∙∙∙█
    // ∙∙█∙
    // ∙█∙∙
    // ∙███
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0fff, 
    0x000f, 
    0x00f0, 
    0x0f00, 
    0x0fff, 
    0x0000, 
    0x0000
};
static const tImage Font1_0x7a = { image_data_Font1_0x7a,
    4, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x7b[10] = {
    // ∙∙∙
    // ∙∙∙
    // ∙██
    // ∙█∙
    // ∙█∙
    // █∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙██
    0x0000, 
    0x0000, 
    0x0ff0, 
    0x0f00, 
    0x0f00, 
    0xf000, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0ff0
};
static const tImage Font1_0x7b = { image_data_Font1_0x7b,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x7c[10] = {
    // ∙∙
    // ∙∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    0x0000, 
    0x0000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000, 
    0xf000
};
static const tImage Font1_0x7c = { image_data_Font1_0x7c,
    2, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x7d[10] = {
    // ∙∙∙
    // ∙∙∙
    // ██∙
    // ∙█∙
    // ∙█∙
    // ∙∙█
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ██∙
    0x0000, 
    0x0000, 
    0xff00, 
    0x0f00, 
    0x0f00, 
    0x00f0, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0xff00
};
static const tImage Font1_0x7d = { image_data_Font1_0x7d,
    3, 10, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Font1_0x7e[20] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ██∙∙∙
    // ∙∙██∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xff00, 0x0000, 
    0x00ff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Font1_0x7e = { image_data_Font1_0x7e,
    5, 10, 16};
#endif


static const tChar Font1_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Font1_0x20},
#else
  // character: ' ' == ''
  {0x20, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &Font1_0x21},
#else
  // character: '!' == ''
  {0x21, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &Font1_0x22},
#else
  // character: '"' == ''
  {0x22, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &Font1_0x23},
#else
  // character: '#' == ''
  {0x23, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &Font1_0x24},
#else
  // character: '$' == ''
  {0x24, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Font1_0x25},
#else
  // character: '%' == ''
  {0x25, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &Font1_0x26},
#else
  // character: '&' == ''
  {0x26, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &Font1_0x27},
#else
  // character: ''' == ''
  {0x27, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &Font1_0x28},
#else
  // character: '(' == ''
  {0x28, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &Font1_0x29},
#else
  // character: ')' == ''
  {0x29, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &Font1_0x2a},
#else
  // character: '*' == ''
  {0x2a, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &Font1_0x2b},
#else
  // character: '+' == ''
  {0x2b, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Font1_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Font1_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Font1_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &Font1_0x2f},
#else
  // character: '/' == ''
  {0x2f, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font1_0x30},
#else
  // character: '0' == ''
  {0x30, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font1_0x31},
#else
  // character: '1' == ''
  {0x31, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font1_0x32},
#else
  // character: '2' == ''
  {0x32, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font1_0x33},
#else
  // character: '3' == ''
  {0x33, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font1_0x34},
#else
  // character: '4' == ''
  {0x34, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font1_0x35},
#else
  // character: '5' == ''
  {0x35, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font1_0x36},
#else
  // character: '6' == ''
  {0x36, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font1_0x37},
#else
  // character: '7' == ''
  {0x37, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font1_0x38},
#else
  // character: '8' == ''
  {0x38, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font1_0x39},
#else
  // character: '9' == ''
  {0x39, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Font1_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &Font1_0x3b},
#else
  // character: ';' == ''
  {0x3b, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &Font1_0x3c},
#else
  // character: '<' == ''
  {0x3c, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &Font1_0x3d},
#else
  // character: '=' == ''
  {0x3d, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &Font1_0x3e},
#else
  // character: '>' == ''
  {0x3e, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &Font1_0x3f},
#else
  // character: '?' == ''
  {0x3f, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &Font1_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Font1_0x41},
#else
  // character: 'A' == ''
  {0x41, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Font1_0x42},
#else
  // character: 'B' == ''
  {0x42, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Font1_0x43},
#else
  // character: 'C' == ''
  {0x43, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Font1_0x44},
#else
  // character: 'D' == ''
  {0x44, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Font1_0x45},
#else
  // character: 'E' == ''
  {0x45, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Font1_0x46},
#else
  // character: 'F' == ''
  {0x46, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Font1_0x47},
#else
  // character: 'G' == ''
  {0x47, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Font1_0x48},
#else
  // character: 'H' == ''
  {0x48, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &Font1_0x49},
#else
  // character: 'I' == ''
  {0x49, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Font1_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Font1_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Font1_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Font1_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Font1_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &Font1_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Font1_0x50},
#else
  // character: 'P' == ''
  {0x50, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Font1_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Font1_0x52},
#else
  // character: 'R' == ''
  {0x52, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Font1_0x53},
#else
  // character: 'S' == ''
  {0x53, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Font1_0x54},
#else
  // character: 'T' == ''
  {0x54, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Font1_0x55},
#else
  // character: 'U' == ''
  {0x55, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Font1_0x56},
#else
  // character: 'V' == ''
  {0x56, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Font1_0x57},
#else
  // character: 'W' == ''
  {0x57, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Font1_0x58},
#else
  // character: 'X' == ''
  {0x58, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Font1_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Font1_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &Font1_0x5b},
#else
  // character: '[' == ''
  {0x5b, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &Font1_0x5c},
#else
  // character: '\' == ''
  {0x5c, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &Font1_0x5d},
#else
  // character: ']' == ''
  {0x5d, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &Font1_0x5e},
#else
  // character: '^' == ''
  {0x5e, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &Font1_0x5f},
#else
  // character: '_' == ''
  {0x5f, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &Font1_0x60},
#else
  // character: '`' == ''
  {0x60, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Font1_0x61},
#else
  // character: 'a' == ''
  {0x61, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &Font1_0x62},
#else
  // character: 'b' == ''
  {0x62, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Font1_0x63},
#else
  // character: 'c' == ''
  {0x63, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &Font1_0x64},
#else
  // character: 'd' == ''
  {0x64, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &Font1_0x65},
#else
  // character: 'e' == ''
  {0x65, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &Font1_0x66},
#else
  // character: 'f' == ''
  {0x66, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &Font1_0x67},
#else
  // character: 'g' == ''
  {0x67, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Font1_0x68},
#else
  // character: 'h' == ''
  {0x68, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &Font1_0x69},
#else
  // character: 'i' == ''
  {0x69, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &Font1_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &Font1_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &Font1_0x},
#endif

#if (0x069 == 0x0)
  // character: 'l'
  {0x6c, &Font1_0x6c},
#else
  // character: 'l' == 'i'
  {0x6c, &Font1_0x69},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Font1_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &Font1_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &Font1_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &Font1_0x70},
#else
  // character: 'p' == ''
  {0x70, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &Font1_0x71},
#else
  // character: 'q' == ''
  {0x71, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &Font1_0x72},
#else
  // character: 'r' == ''
  {0x72, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &Font1_0x73},
#else
  // character: 's' == ''
  {0x73, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &Font1_0x74},
#else
  // character: 't' == ''
  {0x74, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &Font1_0x75},
#else
  // character: 'u' == ''
  {0x75, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &Font1_0x76},
#else
  // character: 'v' == ''
  {0x76, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &Font1_0x77},
#else
  // character: 'w' == ''
  {0x77, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &Font1_0x78},
#else
  // character: 'x' == ''
  {0x78, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &Font1_0x79},
#else
  // character: 'y' == ''
  {0x79, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &Font1_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &Font1_0x7b},
#else
  // character: '{' == ''
  {0x7b, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &Font1_0x7c},
#else
  // character: '|' == ''
  {0x7c, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &Font1_0x7d},
#else
  // character: '}' == ''
  {0x7d, &Font1_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &Font1_0x7e}
#else
  // character: '~' == ''
  {0x7e, &Font1_0x}
#endif

};


const tFont Font8Bold = { 95, Font1_array };

