
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: C:/Users/Borys Kuzmenko/Desktop/Regular/Regular_8.xml
* name: Regular_8
* family: Microsoft Sans Serif
* size: 8
* style: Regular
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Grayscale 4
* data block size: 16 bit(s), uint16_t
* RLE compression enabled: no
* conversion type: Grayscale, not_used not_used
* split to rows: yes
* bits per pixel: 4
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint16_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>
#include "fonts.h"


#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x20[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x20 = { image_data_Regular_8_0x20,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x21[8] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x21 = { image_data_Regular_8_0x21,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x22[16] = {
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x22 = { image_data_Regular_8_0x22,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x23[16] = {
    // ∙∙█∙█∙
    // ∙∙█∙█∙
    // ∙████∙
    // ∙∙█∙█∙
    // ∙███∙∙
    // ∙█∙█∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00f0, 0xf000, 
    0x00f0, 0xf000, 
    0x0fff, 0xf000, 
    0x00f0, 0xf000, 
    0x0fff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x23 = { image_data_Regular_8_0x23,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x24[16] = {
    // ∙∙██∙∙
    // ∙█∙██∙
    // ∙∙█∙∙∙
    // ∙∙∙██∙
    // ∙█∙██∙
    // ∙∙███∙
    // ∙∙∙█∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0x0000, 
    0x0f0f, 0xf000, 
    0x00f0, 0x0000, 
    0x000f, 0xf000, 
    0x0f0f, 0xf000, 
    0x00ff, 0xf000, 
    0x000f, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x24 = { image_data_Regular_8_0x24,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x25[24] = {
    // ∙∙██∙█∙∙∙
    // ∙█∙█∙█∙∙∙
    // ∙████∙∙∙∙
    // ∙∙∙∙███∙∙
    // ∙∙∙█∙█∙█∙
    // ∙∙∙█∙███∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00ff, 0x0f00, 0x0000, 
    0x0f0f, 0x0f00, 0x0000, 
    0x0fff, 0xf000, 0x0000, 
    0x0000, 0xfff0, 0x0000, 
    0x000f, 0x0f0f, 0x0000, 
    0x000f, 0x0fff, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Regular_8_0x25 = { image_data_Regular_8_0x25,
    9, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x26[16] = {
    // ∙∙∙█∙∙∙
    // ∙∙█∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙██∙█∙
    // ∙█∙∙██∙
    // ∙∙████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x000f, 0x0000, 
    0x00f0, 0xf000, 
    0x000f, 0x0000, 
    0x00ff, 0x0f00, 
    0x0f00, 0xff00, 
    0x00ff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x26 = { image_data_Regular_8_0x26,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x27[8] = {
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x27 = { image_data_Regular_8_0x27,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x28[8] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0f00, 
    0x0f00, 
    0x00f0, 
    0x00f0, 
    0x00f0
};
static const tImage Regular_8_0x28 = { image_data_Regular_8_0x28,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x29[8] = {
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙█∙∙
    0x0f00, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0f00
};
static const tImage Regular_8_0x29 = { image_data_Regular_8_0x29,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x2a[16] = {
    // ∙∙█∙∙
    // ∙███∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00f0, 0x0000, 
    0x0fff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x2a = { image_data_Regular_8_0x2a,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x2b[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙████∙
    // ∙∙∙█∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x0fff, 0xf000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x2b = { image_data_Regular_8_0x2b,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x2c[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x00f0, 
    0x00f0, 
    0x0000
};
static const tImage Regular_8_0x2c = { image_data_Regular_8_0x2c,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x2d[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0ff0, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x2d = { image_data_Regular_8_0x2d,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x2e[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x2e = { image_data_Regular_8_0x2e,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x2f[8] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x2f = { image_data_Regular_8_0x2f,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x30[16] = {
    // ∙∙██∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0x0000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x30 = { image_data_Regular_8_0x30,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x31[8] = {
    // ∙∙█∙
    // ∙██∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00f0, 
    0x0ff0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x31 = { image_data_Regular_8_0x31,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x32[16] = {
    // ∙∙██∙∙
    // ∙█∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙█∙∙
    // ∙∙█∙∙∙
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0x0000, 
    0x0f00, 0xf000, 
    0x0000, 0xf000, 
    0x000f, 0x0000, 
    0x00f0, 0x0000, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x32 = { image_data_Regular_8_0x32,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x33[16] = {
    // ∙∙██∙∙
    // ∙█∙∙█∙
    // ∙∙∙██∙
    // ∙∙∙∙█∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0x0000, 
    0x0f00, 0xf000, 
    0x000f, 0xf000, 
    0x0000, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x33 = { image_data_Regular_8_0x33,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x34[16] = {
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙∙██∙∙
    // ∙█∙█∙∙
    // ∙████∙
    // ∙∙∙█∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x00ff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0fff, 0xf000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x34 = { image_data_Regular_8_0x34,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x35[16] = {
    // ∙∙███∙
    // ∙∙█∙∙∙
    // ∙∙██∙∙
    // ∙∙∙∙█∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0xf000, 
    0x00f0, 0x0000, 
    0x00ff, 0x0000, 
    0x0000, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x35 = { image_data_Regular_8_0x35,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x36[16] = {
    // ∙∙██∙∙
    // ∙█∙∙█∙
    // ∙███∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0x0000, 
    0x0f00, 0xf000, 
    0x0fff, 0x0000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x36 = { image_data_Regular_8_0x36,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x37[16] = {
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙∙█∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0fff, 0xf000, 
    0x0000, 0xf000, 
    0x0000, 0xf000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x00f0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x37 = { image_data_Regular_8_0x37,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x38[16] = {
    // ∙∙██∙∙
    // ∙█∙∙█∙
    // ∙∙█∙█∙
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0x0000, 
    0x0f00, 0xf000, 
    0x00f0, 0xf000, 
    0x00ff, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x38 = { image_data_Regular_8_0x38,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x39[16] = {
    // ∙∙██∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙∙██∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0x0000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x39 = { image_data_Regular_8_0x39,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x3a[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x00f0, 
    0x0000, 
    0x0000, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x3a = { image_data_Regular_8_0x3a,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x3b[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x00f0, 
    0x0000, 
    0x0000, 
    0x00f0, 
    0x00f0, 
    0x0000
};
static const tImage Regular_8_0x3b = { image_data_Regular_8_0x3b,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x3c[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙█∙
    // ∙∙██∙∙
    // ∙██∙∙∙
    // ∙∙∙██∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0xf000, 
    0x00ff, 0x0000, 
    0x0ff0, 0x0000, 
    0x000f, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x3c = { image_data_Regular_8_0x3c,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x3d[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x3d = { image_data_Regular_8_0x3d,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x3e[16] = {
    // ∙∙∙∙∙∙
    // ∙█∙∙∙∙
    // ∙∙██∙∙
    // ∙∙∙██∙
    // ∙██∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0f00, 0x0000, 
    0x00ff, 0x0000, 
    0x000f, 0xf000, 
    0x0ff0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x3e = { image_data_Regular_8_0x3e,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x3f[16] = {
    // ∙∙██∙∙
    // ∙█∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0x0000, 
    0x0f00, 0xf000, 
    0x0000, 0xf000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x3f = { image_data_Regular_8_0x3f,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x40[24] = {
    // ∙∙∙████∙∙∙
    // ∙∙█∙∙∙∙█∙∙
    // ∙∙█∙███∙█∙
    // ∙█∙█∙∙█∙█∙
    // ∙█∙█∙∙█∙█∙
    // ∙█∙█████∙∙
    // ∙∙█∙∙∙∙∙∙∙
    // ∙∙∙████∙∙∙
    0x000f, 0xfff0, 0x0000, 
    0x00f0, 0x000f, 0x0000, 
    0x00f0, 0xfff0, 0xf000, 
    0x0f0f, 0x00f0, 0xf000, 
    0x0f0f, 0x00f0, 0xf000, 
    0x0f0f, 0xffff, 0x0000, 
    0x00f0, 0x0000, 0x0000, 
    0x000f, 0xfff0, 0x0000
};
static const tImage Regular_8_0x40 = { image_data_Regular_8_0x40,
    10, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x41[16] = {
    // ∙∙∙█∙∙∙
    // ∙∙∙██∙∙
    // ∙∙█∙█∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x000f, 0x0000, 
    0x000f, 0xf000, 
    0x00f0, 0xf000, 
    0x00ff, 0xf000, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x41 = { image_data_Regular_8_0x41,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x42[16] = {
    // ∙███∙∙
    // ∙█∙∙█∙
    // ∙█∙█∙∙
    // ∙██∙█∙
    // ∙█∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0fff, 0x0000, 
    0x0f00, 0xf000, 
    0x0f0f, 0x0000, 
    0x0ff0, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x42 = { image_data_Regular_8_0x42,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x43[16] = {
    // ∙∙∙██∙∙
    // ∙∙█∙∙█∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙∙█∙∙█∙
    // ∙∙████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x000f, 0xf000, 
    0x00f0, 0x0f00, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x00f0, 0x0f00, 
    0x00ff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x43 = { image_data_Regular_8_0x43,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x44[16] = {
    // ∙███∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0fff, 0x0000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x44 = { image_data_Regular_8_0x44,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x45[16] = {
    // ∙████∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙████∙
    // ∙█∙∙∙∙
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x45 = { image_data_Regular_8_0x45,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x46[16] = {
    // ∙████∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙███∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x46 = { image_data_Regular_8_0x46,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x47[16] = {
    // ∙∙∙███∙∙
    // ∙∙█∙∙∙█∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙███∙
    // ∙∙█∙∙∙█∙
    // ∙∙█████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x000f, 0xff00, 
    0x00f0, 0x00f0, 
    0x0f00, 0x0000, 
    0x0f00, 0xfff0, 
    0x00f0, 0x00f0, 
    0x00ff, 0xfff0, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x47 = { image_data_Regular_8_0x47,
    8, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x48[16] = {
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙████∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x48 = { image_data_Regular_8_0x48,
    6, 8, 16};
#endif

#if (0x021 == 0x0)
static const uint16_t image_data_Regular_8_0x49[8] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x49 = { image_data_Regular_8_0x49,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x4a[16] = {
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙█∙█∙
    // ∙∙██∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x0f0f, 0x0000, 
    0x00ff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x4a = { image_data_Regular_8_0x4a,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x4b[16] = {
    // ∙█∙∙█∙
    // ∙█∙█∙∙
    // ∙██∙∙∙
    // ∙█∙█∙∙
    // ∙█∙█∙∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0f00, 0xf000, 
    0x0f0f, 0x0000, 
    0x0ff0, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x4b = { image_data_Regular_8_0x4b,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x4c[16] = {
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x4c = { image_data_Regular_8_0x4c,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x4d[16] = {
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙██∙██∙
    // ∙██∙██∙
    // ∙███∙█∙
    // ∙█∙█∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0f00, 0x0f00, 
    0x0f00, 0xff00, 
    0x0ff0, 0xff00, 
    0x0ff0, 0xff00, 
    0x0fff, 0x0f00, 
    0x0f0f, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x4d = { image_data_Regular_8_0x4d,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x4e[16] = {
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙██∙█∙
    // ∙█∙██∙
    // ∙█∙██∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0ff0, 0xf000, 
    0x0f0f, 0xf000, 
    0x0f0f, 0xf000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x4e = { image_data_Regular_8_0x4e,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x4f[16] = {
    // ∙∙∙███∙∙
    // ∙∙█∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x000f, 0xff00, 
    0x00f0, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x00f0, 0x00f0, 
    0x00ff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x4f = { image_data_Regular_8_0x4f,
    8, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x50[16] = {
    // ∙███∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙███∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0fff, 0x0000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x50 = { image_data_Regular_8_0x50,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x51[16] = {
    // ∙∙∙███∙∙
    // ∙∙█∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█∙█∙█∙
    // ∙∙█████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x000f, 0xff00, 
    0x00f0, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x00f0, 0xf0f0, 
    0x00ff, 0xfff0, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x51 = { image_data_Regular_8_0x51,
    8, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x52[16] = {
    // ∙████∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙███∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0fff, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0x0000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x52 = { image_data_Regular_8_0x52,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x53[16] = {
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙∙██∙∙∙
    // ∙∙∙∙██∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00ff, 0xf000, 
    0x0f00, 0x0f00, 
    0x00ff, 0x0000, 
    0x0000, 0xff00, 
    0x0f00, 0x0f00, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x53 = { image_data_Regular_8_0x53,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x54[16] = {
    // ∙█████∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0fff, 0xff00, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x54 = { image_data_Regular_8_0x54,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x55[16] = {
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x55 = { image_data_Regular_8_0x55,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x56[16] = {
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙█∙∙█∙
    // ∙∙█∙█∙∙
    // ∙∙∙██∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x00f0, 0x0f00, 
    0x00f0, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x56 = { image_data_Regular_8_0x56,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x57[24] = {
    // ∙█∙∙█∙∙█∙
    // ∙█∙∙██∙█∙
    // ∙∙█∙██∙█∙
    // ∙∙██∙█∙█∙
    // ∙∙██∙∙█∙∙
    // ∙∙∙█∙∙█∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x0f00, 0xf00f, 0x0000, 
    0x0f00, 0xff0f, 0x0000, 
    0x00f0, 0xff0f, 0x0000, 
    0x00ff, 0x0f0f, 0x0000, 
    0x00ff, 0x00f0, 0x0000, 
    0x000f, 0x00f0, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Regular_8_0x57 = { image_data_Regular_8_0x57,
    9, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x58[16] = {
    // ∙█∙∙∙█∙
    // ∙∙█∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙█∙█∙∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0f00, 0x0f00, 
    0x00f0, 0xf000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x00f0, 0xf000, 
    0x0f00, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x58 = { image_data_Regular_8_0x58,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x59[16] = {
    // ∙█∙∙∙█∙
    // ∙∙█∙∙█∙
    // ∙∙█∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0f00, 0x0f00, 
    0x00f0, 0x0f00, 
    0x00f0, 0xf000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x59 = { image_data_Regular_8_0x59,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x5a[16] = {
    // ∙█████∙
    // ∙∙∙∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙█∙∙∙∙
    // ∙█████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0fff, 0xff00, 
    0x0000, 0xf000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x00f0, 0x0000, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x5a = { image_data_Regular_8_0x5a,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x5b[8] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0
};
static const tImage Regular_8_0x5b = { image_data_Regular_8_0x5b,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x5c[8] = {
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x5c = { image_data_Regular_8_0x5c,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x5d[8] = {
    // ∙██∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙██∙
    0x0ff0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0ff0
};
static const tImage Regular_8_0x5d = { image_data_Regular_8_0x5d,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x5e[16] = {
    // ∙∙█∙∙
    // ∙∙██∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00f0, 0x0000, 
    0x00ff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x5e = { image_data_Regular_8_0x5e,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x5f[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x5f = { image_data_Regular_8_0x5f,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x60[8] = {
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0ff0, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x60 = { image_data_Regular_8_0x60,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x61[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x00ff, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x61 = { image_data_Regular_8_0x61,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x62[16] = {
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙███∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x62 = { image_data_Regular_8_0x62,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x63[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙███∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0xf000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x63 = { image_data_Regular_8_0x63,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x64[16] = {
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0xf000, 
    0x0000, 0xf000, 
    0x00ff, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x64 = { image_data_Regular_8_0x64,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x65[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙███∙
    // ∙████∙
    // ∙█∙∙∙∙
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0xf000, 
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x65 = { image_data_Regular_8_0x65,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x66[8] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙██∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00f0, 
    0x00f0, 
    0x0ff0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x66 = { image_data_Regular_8_0x66,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x67[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙∙██∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0x0000
};
static const tImage Regular_8_0x67 = { image_data_Regular_8_0x67,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x68[16] = {
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙███∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x68 = { image_data_Regular_8_0x68,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x69[8] = {
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00f0, 
    0x0000, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x69 = { image_data_Regular_8_0x69,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x6a[8] = {
    // ∙█∙∙
    // ∙∙∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    0x0f00, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00
};
static const tImage Regular_8_0x6a = { image_data_Regular_8_0x6a,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x6b[16] = {
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙███∙
    // ∙█∙∙∙
    // ∙██∙∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0x0000, 
    0x0f00, 0x0000, 
    0x0ff0, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x6b = { image_data_Regular_8_0x6b,
    5, 8, 16};
#endif

#if (0x021 == 0x0)
static const uint16_t image_data_Regular_8_0x6c[8] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x6c = { image_data_Regular_8_0x6c,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x6d[16] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█████∙
    // ∙█∙█∙█∙
    // ∙█∙█∙█∙
    // ∙█∙█∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xff00, 
    0x0f0f, 0x0f00, 
    0x0f0f, 0x0f00, 
    0x0f0f, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x6d = { image_data_Regular_8_0x6d,
    7, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x6e[16] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙███∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x6e = { image_data_Regular_8_0x6e,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x6f[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x6f = { image_data_Regular_8_0x6f,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x70[16] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙███∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙███∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0fff, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000
};
static const tImage Regular_8_0x70 = { image_data_Regular_8_0x70,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x71[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙███∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x00ff, 0xf000, 
    0x0000, 0xf000, 
    0x0000, 0xf000
};
static const tImage Regular_8_0x71 = { image_data_Regular_8_0x71,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x72[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙██∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0ff0, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x72 = { image_data_Regular_8_0x72,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x73[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙██∙∙∙
    // ∙∙∙██∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0ff0, 0x0000, 
    0x000f, 0xf000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x73 = { image_data_Regular_8_0x73,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x74[8] = {
    // ∙∙∙∙
    // ∙∙█∙
    // ∙██∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x00f0, 
    0x0ff0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0000, 
    0x0000
};
static const tImage Regular_8_0x74 = { image_data_Regular_8_0x74,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x75[16] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0x0000, 
    0x0fff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x75 = { image_data_Regular_8_0x75,
    5, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x76[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙█∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0xf000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x76 = { image_data_Regular_8_0x76,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x77[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙█∙∙█∙
    // ∙█∙███∙∙
    // ∙∙█∙██∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f0f, 0x00f0, 
    0x0f0f, 0xff00, 
    0x00f0, 0xff00, 
    0x00f0, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x77 = { image_data_Regular_8_0x77,
    8, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x78[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x78 = { image_data_Regular_8_0x78,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x79[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙█∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙█∙∙∙
    // ∙█∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0xf000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x00f0, 0x0000, 
    0x0f00, 0x0000
};
static const tImage Regular_8_0x79 = { image_data_Regular_8_0x79,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x7a[16] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙∙∙█∙∙
    // ∙∙█∙∙∙
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x000f, 0x0000, 
    0x00f0, 0x0000, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x7a = { image_data_Regular_8_0x7a,
    6, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x7b[8] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙██∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0ff0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0
};
static const tImage Regular_8_0x7b = { image_data_Regular_8_0x7b,
    4, 8, 16};
#endif

#if (0x05b == 0x0)
static const uint16_t image_data_Regular_8_0x7c[8] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0
};
static const tImage Regular_8_0x7c = { image_data_Regular_8_0x7c,
    4, 8, 16};
#endif

#if (0x029 == 0x0)
static const uint16_t image_data_Regular_8_0x7d[8] = {
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙█∙∙
    0x0f00, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0f00
};
static const tImage Regular_8_0x7d = { image_data_Regular_8_0x7d,
    4, 8, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Regular_8_0x7e[16] = {
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00ff, 0xf000, 
    0x0f00, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Regular_8_0x7e = { image_data_Regular_8_0x7e,
    6, 8, 16};
#endif


static const tChar Regular_8_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Regular_8_0x20},
#else
  // character: ' ' == ''
  {0x20, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &Regular_8_0x21},
#else
  // character: '!' == ''
  {0x21, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &Regular_8_0x22},
#else
  // character: '"' == ''
  {0x22, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &Regular_8_0x23},
#else
  // character: '#' == ''
  {0x23, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &Regular_8_0x24},
#else
  // character: '$' == ''
  {0x24, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Regular_8_0x25},
#else
  // character: '%' == ''
  {0x25, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &Regular_8_0x26},
#else
  // character: '&' == ''
  {0x26, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &Regular_8_0x27},
#else
  // character: ''' == ''
  {0x27, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &Regular_8_0x28},
#else
  // character: '(' == ''
  {0x28, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &Regular_8_0x29},
#else
  // character: ')' == ''
  {0x29, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &Regular_8_0x2a},
#else
  // character: '*' == ''
  {0x2a, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &Regular_8_0x2b},
#else
  // character: '+' == ''
  {0x2b, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Regular_8_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Regular_8_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Regular_8_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &Regular_8_0x2f},
#else
  // character: '/' == ''
  {0x2f, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Regular_8_0x30},
#else
  // character: '0' == ''
  {0x30, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Regular_8_0x31},
#else
  // character: '1' == ''
  {0x31, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Regular_8_0x32},
#else
  // character: '2' == ''
  {0x32, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Regular_8_0x33},
#else
  // character: '3' == ''
  {0x33, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Regular_8_0x34},
#else
  // character: '4' == ''
  {0x34, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Regular_8_0x35},
#else
  // character: '5' == ''
  {0x35, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Regular_8_0x36},
#else
  // character: '6' == ''
  {0x36, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Regular_8_0x37},
#else
  // character: '7' == ''
  {0x37, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Regular_8_0x38},
#else
  // character: '8' == ''
  {0x38, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Regular_8_0x39},
#else
  // character: '9' == ''
  {0x39, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Regular_8_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &Regular_8_0x3b},
#else
  // character: ';' == ''
  {0x3b, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &Regular_8_0x3c},
#else
  // character: '<' == ''
  {0x3c, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &Regular_8_0x3d},
#else
  // character: '=' == ''
  {0x3d, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &Regular_8_0x3e},
#else
  // character: '>' == ''
  {0x3e, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &Regular_8_0x3f},
#else
  // character: '?' == ''
  {0x3f, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &Regular_8_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Regular_8_0x41},
#else
  // character: 'A' == ''
  {0x41, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Regular_8_0x42},
#else
  // character: 'B' == ''
  {0x42, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Regular_8_0x43},
#else
  // character: 'C' == ''
  {0x43, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Regular_8_0x44},
#else
  // character: 'D' == ''
  {0x44, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Regular_8_0x45},
#else
  // character: 'E' == ''
  {0x45, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Regular_8_0x46},
#else
  // character: 'F' == ''
  {0x46, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Regular_8_0x47},
#else
  // character: 'G' == ''
  {0x47, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Regular_8_0x48},
#else
  // character: 'H' == ''
  {0x48, &Regular_8_0x},
#endif

#if (0x021 == 0x0)
  // character: 'I'
  {0x49, &Regular_8_0x49},
#else
  // character: 'I' == '!'
  {0x49, &Regular_8_0x21},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Regular_8_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Regular_8_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Regular_8_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Regular_8_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Regular_8_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &Regular_8_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Regular_8_0x50},
#else
  // character: 'P' == ''
  {0x50, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Regular_8_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Regular_8_0x52},
#else
  // character: 'R' == ''
  {0x52, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Regular_8_0x53},
#else
  // character: 'S' == ''
  {0x53, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Regular_8_0x54},
#else
  // character: 'T' == ''
  {0x54, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Regular_8_0x55},
#else
  // character: 'U' == ''
  {0x55, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Regular_8_0x56},
#else
  // character: 'V' == ''
  {0x56, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Regular_8_0x57},
#else
  // character: 'W' == ''
  {0x57, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Regular_8_0x58},
#else
  // character: 'X' == ''
  {0x58, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Regular_8_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Regular_8_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &Regular_8_0x5b},
#else
  // character: '[' == ''
  {0x5b, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &Regular_8_0x5c},
#else
  // character: '\' == ''
  {0x5c, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &Regular_8_0x5d},
#else
  // character: ']' == ''
  {0x5d, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &Regular_8_0x5e},
#else
  // character: '^' == ''
  {0x5e, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &Regular_8_0x5f},
#else
  // character: '_' == ''
  {0x5f, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &Regular_8_0x60},
#else
  // character: '`' == ''
  {0x60, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Regular_8_0x61},
#else
  // character: 'a' == ''
  {0x61, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &Regular_8_0x62},
#else
  // character: 'b' == ''
  {0x62, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Regular_8_0x63},
#else
  // character: 'c' == ''
  {0x63, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &Regular_8_0x64},
#else
  // character: 'd' == ''
  {0x64, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &Regular_8_0x65},
#else
  // character: 'e' == ''
  {0x65, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &Regular_8_0x66},
#else
  // character: 'f' == ''
  {0x66, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &Regular_8_0x67},
#else
  // character: 'g' == ''
  {0x67, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Regular_8_0x68},
#else
  // character: 'h' == ''
  {0x68, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &Regular_8_0x69},
#else
  // character: 'i' == ''
  {0x69, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &Regular_8_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &Regular_8_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &Regular_8_0x},
#endif

#if (0x021 == 0x0)
  // character: 'l'
  {0x6c, &Regular_8_0x6c},
#else
  // character: 'l' == '!'
  {0x6c, &Regular_8_0x21},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Regular_8_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &Regular_8_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &Regular_8_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &Regular_8_0x70},
#else
  // character: 'p' == ''
  {0x70, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &Regular_8_0x71},
#else
  // character: 'q' == ''
  {0x71, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &Regular_8_0x72},
#else
  // character: 'r' == ''
  {0x72, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &Regular_8_0x73},
#else
  // character: 's' == ''
  {0x73, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &Regular_8_0x74},
#else
  // character: 't' == ''
  {0x74, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &Regular_8_0x75},
#else
  // character: 'u' == ''
  {0x75, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &Regular_8_0x76},
#else
  // character: 'v' == ''
  {0x76, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &Regular_8_0x77},
#else
  // character: 'w' == ''
  {0x77, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &Regular_8_0x78},
#else
  // character: 'x' == ''
  {0x78, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &Regular_8_0x79},
#else
  // character: 'y' == ''
  {0x79, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &Regular_8_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &Regular_8_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &Regular_8_0x7b},
#else
  // character: '{' == ''
  {0x7b, &Regular_8_0x},
#endif

#if (0x05b == 0x0)
  // character: '|'
  {0x7c, &Regular_8_0x7c},
#else
  // character: '|' == '['
  {0x7c, &Regular_8_0x5b},
#endif

#if (0x029 == 0x0)
  // character: '}'
  {0x7d, &Regular_8_0x7d},
#else
  // character: '}' == ')'
  {0x7d, &Regular_8_0x29},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &Regular_8_0x7e}
#else
  // character: '~' == ''
  {0x7e, &Regular_8_0x}
#endif

};


const tFont Regular_8 = { 95, Regular_8_array };

