
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: C:/Users/Borys Kuzmenko/Desktop/Roboto/Roboto_M_12.xml
* name: Roboto_M_12
* family: Roboto Medium
* size: 12
* style: Regular
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Grayscale 4
* data block size: 16 bit(s), uint16_t
* RLE compression enabled: no
* conversion type: Grayscale, not_used not_used
* split to rows: yes
* bits per pixel: 4
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint16_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>
#include "fonts.h"


#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x20[11] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x20 = { image_data_Roboto_M_12_0x20,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x21[11] = {
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x21 = { image_data_Roboto_M_12_0x21,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x22[11] = {
    // ∙██∙
    // ∙██∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0ff0, 
    0x0ff0, 
    0x00f0, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x22 = { image_data_Roboto_M_12_0x22,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x23[22] = {
    // ∙∙∙█∙█∙
    // ∙∙∙█∙█∙
    // ∙∙∙█∙█∙
    // ∙██████
    // ∙∙█∙█∙∙
    // ███████
    // ∙∙█∙█∙∙
    // ∙∙█∙█∙∙
    // ∙∙█∙█∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x000f, 0x0f00, 
    0x000f, 0x0f00, 
    0x000f, 0x0f00, 
    0x0fff, 0xfff0, 
    0x00f0, 0xf000, 
    0xffff, 0xfff0, 
    0x00f0, 0xf000, 
    0x00f0, 0xf000, 
    0x00f0, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x23 = { image_data_Roboto_M_12_0x23,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x24[22] = {
    // ∙∙███∙∙
    // ∙██∙██∙
    // ∙█∙∙∙█∙
    // ∙██∙∙∙∙
    // ∙∙███∙∙
    // ∙∙∙∙██∙
    // ∙█∙∙∙█∙
    // ∙██∙██∙
    // ∙∙███∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    0x00ff, 0xf000, 
    0x0ff0, 0xff00, 
    0x0f00, 0x0f00, 
    0x0ff0, 0x0000, 
    0x00ff, 0xf000, 
    0x0000, 0xff00, 
    0x0f00, 0x0f00, 
    0x0ff0, 0xff00, 
    0x00ff, 0xf000, 
    0x000f, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x24 = { image_data_Roboto_M_12_0x24,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x25[33] = {
    // ∙███∙∙∙∙∙
    // ∙█∙█∙∙█∙∙
    // ∙█∙█∙█∙∙∙
    // ∙███∙█∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙█∙███∙
    // ∙∙∙█∙█∙█∙
    // ∙∙█∙∙█∙█∙
    // ∙∙∙∙∙███∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x0fff, 0x0000, 0x0000, 
    0x0f0f, 0x00f0, 0x0000, 
    0x0f0f, 0x0f00, 0x0000, 
    0x0fff, 0x0f00, 0x0000, 
    0x0000, 0xf000, 0x0000, 
    0x000f, 0x0fff, 0x0000, 
    0x000f, 0x0f0f, 0x0000, 
    0x00f0, 0x0f0f, 0x0000, 
    0x0000, 0x0fff, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Roboto_M_12_0x25 = { image_data_Roboto_M_12_0x25,
    9, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x26[22] = {
    // ∙∙███∙∙∙
    // ∙██∙██∙∙
    // ∙██∙█∙∙∙
    // ∙∙███∙∙∙
    // ∙∙██∙∙∙∙
    // ∙█∙██∙█∙
    // ∙█∙∙███∙
    // ∙█∙∙∙█∙∙
    // ∙∙███∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00ff, 0xf000, 
    0x0ff0, 0xff00, 
    0x0ff0, 0xf000, 
    0x00ff, 0xf000, 
    0x00ff, 0x0000, 
    0x0f0f, 0xf0f0, 
    0x0f00, 0xfff0, 
    0x0f00, 0x0f00, 
    0x00ff, 0xf0f0, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x26 = { image_data_Roboto_M_12_0x26,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x27[11] = {
    // ██
    // ██
    // █∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    0xff00, 
    0xff00, 
    0xf000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x27 = { image_data_Roboto_M_12_0x27,
    2, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x28[11] = {
    // ∙∙█∙
    // ∙∙█∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙█∙
    0x00f0, 
    0x00f0, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x00f0, 
    0x00f0
};
static const tImage Roboto_M_12_0x28 = { image_data_Roboto_M_12_0x28,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x29[11] = {
    // ∙█∙∙
    // ∙██∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙██∙
    // ∙█∙∙
    0x0f00, 
    0x0ff0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x00f0, 
    0x0ff0, 
    0x0f00
};
static const tImage Roboto_M_12_0x29 = { image_data_Roboto_M_12_0x29,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x2a[22] = {
    // ∙∙█∙∙
    // █∙█∙∙
    // ∙████
    // ∙███∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00f0, 0x0000, 
    0xf0f0, 0x0000, 
    0x0fff, 0xf000, 
    0x0fff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x2a = { image_data_Roboto_M_12_0x2a,
    5, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x2b[22] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ██████∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0xffff, 0xff00, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x2b = { image_data_Roboto_M_12_0x2b,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x2c[11] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // █∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0xf000
};
static const tImage Roboto_M_12_0x2c = { image_data_Roboto_M_12_0x2c,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x2d[11] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ████
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0xffff, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x2d = { image_data_Roboto_M_12_0x2d,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x2e[11] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x2e = { image_data_Roboto_M_12_0x2e,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x2f[22] = {
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙██∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙██∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ██∙∙∙
    // █∙∙∙∙
    // ∙∙∙∙∙
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x00ff, 0x0000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x0ff0, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0xff00, 0x0000, 
    0xf000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x2f = { image_data_Roboto_M_12_0x2f,
    5, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x30[22] = {
    // ∙∙███∙∙
    // ∙██∙██∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙██∙██∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00ff, 0xf000, 
    0x0ff0, 0xff00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0ff0, 0xff00, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x30 = { image_data_Roboto_M_12_0x30,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x31[22] = {
    // ∙∙∙██∙∙
    // ∙████∙∙
    // ∙∙∙██∙∙
    // ∙∙∙██∙∙
    // ∙∙∙██∙∙
    // ∙∙∙██∙∙
    // ∙∙∙██∙∙
    // ∙∙∙██∙∙
    // ∙∙∙██∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x000f, 0xf000, 
    0x0fff, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x31 = { image_data_Roboto_M_12_0x31,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x32[22] = {
    // ∙∙███∙∙
    // ∙█∙∙██∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙██∙
    // ∙∙∙∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙██∙∙∙
    // ∙██∙∙∙∙
    // ∙█████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00ff, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0x0000, 0xff00, 
    0x0000, 0xf000, 
    0x000f, 0x0000, 
    0x00ff, 0x0000, 
    0x0ff0, 0x0000, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x32 = { image_data_Roboto_M_12_0x32,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x33[22] = {
    // ∙████∙∙
    // ∙█∙∙██∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙██∙
    // ∙∙███∙∙
    // ∙∙∙∙██∙
    // ∙∙∙∙∙█∙
    // ∙█∙∙██∙
    // ∙████∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0fff, 0xf000, 
    0x0f00, 0xff00, 
    0x0000, 0x0f00, 
    0x0000, 0xff00, 
    0x00ff, 0xf000, 
    0x0000, 0xff00, 
    0x0000, 0x0f00, 
    0x0f00, 0xff00, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x33 = { image_data_Roboto_M_12_0x33,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x34[22] = {
    // ∙∙∙∙█∙∙
    // ∙∙∙██∙∙
    // ∙∙∙██∙∙
    // ∙∙█∙█∙∙
    // ∙██∙█∙∙
    // ∙█∙∙█∙∙
    // ███████
    // ∙∙∙∙█∙∙
    // ∙∙∙∙█∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x00f0, 0xf000, 
    0x0ff0, 0xf000, 
    0x0f00, 0xf000, 
    0xffff, 0xfff0, 
    0x0000, 0xf000, 
    0x0000, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x34 = { image_data_Roboto_M_12_0x34,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x35[22] = {
    // ∙█████∙
    // ∙██∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙████∙∙
    // ∙∙∙∙██∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙█∙∙██∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0fff, 0xff00, 
    0x0ff0, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0000, 0xff00, 
    0x0000, 0x0f00, 
    0x0000, 0x0f00, 
    0x0f00, 0xff00, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x35 = { image_data_Roboto_M_12_0x35,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x36[22] = {
    // ∙∙∙██∙∙
    // ∙∙█∙∙∙∙
    // ∙██∙∙∙∙
    // ∙████∙∙
    // ∙██∙██∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙██∙██∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x000f, 0xf000, 
    0x00f0, 0x0000, 
    0x0ff0, 0x0000, 
    0x0fff, 0xf000, 
    0x0ff0, 0xff00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0ff0, 0xff00, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x36 = { image_data_Roboto_M_12_0x36,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x37[22] = {
    // ██████∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙██∙
    // ∙∙∙∙█∙∙
    // ∙∙∙██∙∙
    // ∙∙∙█∙∙∙
    // ∙∙██∙∙∙
    // ∙∙██∙∙∙
    // ∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0xffff, 0xff00, 
    0x0000, 0x0f00, 
    0x0000, 0xff00, 
    0x0000, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0x0000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x00f0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x37 = { image_data_Roboto_M_12_0x37,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x38[22] = {
    // ∙∙███∙∙
    // ∙██∙██∙
    // ∙█∙∙∙█∙
    // ∙██∙██∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00ff, 0xf000, 
    0x0ff0, 0xff00, 
    0x0f00, 0x0f00, 
    0x0ff0, 0xff00, 
    0x00ff, 0xf000, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0xff00, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x38 = { image_data_Roboto_M_12_0x38,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x39[22] = {
    // ∙∙███∙∙
    // ∙█∙∙██∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙∙██∙█∙
    // ∙∙∙∙██∙
    // ∙∙∙██∙∙
    // ∙∙██∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00ff, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0xff00, 
    0x00ff, 0x0f00, 
    0x0000, 0xff00, 
    0x000f, 0xf000, 
    0x00ff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x39 = { image_data_Roboto_M_12_0x39,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x3a[11] = {
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x3a = { image_data_Roboto_M_12_0x3a,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x3b[11] = {
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // █∙∙
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0xf000
};
static const tImage Roboto_M_12_0x3b = { image_data_Roboto_M_12_0x3b,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x3c[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙█∙
    // ∙∙███∙
    // ██∙∙∙∙
    // ∙∙███∙
    // ∙∙∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0xf000, 
    0x00ff, 0xf000, 
    0xff00, 0x0000, 
    0x00ff, 0xf000, 
    0x0000, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x3c = { image_data_Roboto_M_12_0x3c,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x3d[22] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x3d = { image_data_Roboto_M_12_0x3d,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x3e[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙∙∙
    // ∙████∙
    // ∙∙∙∙██
    // ∙████∙
    // ∙█∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0000, 0xff00, 
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x3e = { image_data_Roboto_M_12_0x3e,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x3f[22] = {
    // ∙████∙
    // ██∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙██∙
    // ∙∙██∙∙
    // ∙∙█∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙██∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0fff, 0xf000, 
    0xff00, 0xf000, 
    0x0000, 0xf000, 
    0x000f, 0xf000, 
    0x00ff, 0x0000, 
    0x00f0, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x3f = { image_data_Roboto_M_12_0x3f,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x40[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙█████∙∙∙
    // ∙∙█∙∙∙∙∙█∙∙
    // ∙██∙∙∙∙∙∙█∙
    // ∙█∙∙███∙∙█∙
    // ∙█∙∙█∙█∙∙█∙
    // ∙█∙█∙∙█∙∙█∙
    // ∙█∙█∙∙█∙∙█∙
    // ∙█∙∙█████∙∙
    // ∙█∙∙∙∙∙∙∙∙∙
    // ∙∙█∙∙∙∙∙∙∙∙
    0x0000, 0x0000, 0x0000, 
    0x000f, 0xffff, 0x0000, 
    0x00f0, 0x0000, 0xf000, 
    0x0ff0, 0x0000, 0x0f00, 
    0x0f00, 0xfff0, 0x0f00, 
    0x0f00, 0xf0f0, 0x0f00, 
    0x0f0f, 0x00f0, 0x0f00, 
    0x0f0f, 0x00f0, 0x0f00, 
    0x0f00, 0xffff, 0xf000, 
    0x0f00, 0x0000, 0x0000, 
    0x00f0, 0x0000, 0x0000
};
static const tImage Roboto_M_12_0x40 = { image_data_Roboto_M_12_0x40,
    11, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x41[22] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙████∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙██∙∙██∙
    // ∙██████∙
    // ∙█∙∙∙∙█∙
    // ██∙∙∙∙██
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x00ff, 0xff00, 
    0x00f0, 0x0f00, 
    0x00f0, 0x0f00, 
    0x0ff0, 0x0ff0, 
    0x0fff, 0xfff0, 
    0x0f00, 0x00f0, 
    0xff00, 0x00ff, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x41 = { image_data_Roboto_M_12_0x41,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x42[22] = {
    // ∙█████∙∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙██∙
    // ∙█████∙∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙██∙
    // ∙█████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0fff, 0xff00, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x0ff0, 
    0x0fff, 0xff00, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x0ff0, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x42 = { image_data_Roboto_M_12_0x42,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x43[22] = {
    // ∙∙████∙∙
    // ∙██∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙██∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00ff, 0xff00, 
    0x0ff0, 0x0ff0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x00f0, 
    0x0ff0, 0x0ff0, 
    0x00ff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x43 = { image_data_Roboto_M_12_0x43,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x44[22] = {
    // ∙████∙∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙█∙∙
    // ∙████∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0fff, 0xf000, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x0f00, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x44 = { image_data_Roboto_M_12_0x44,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x45[22] = {
    // ∙█████∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█████∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0fff, 0xff00, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xff00, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x45 = { image_data_Roboto_M_12_0x45,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x46[22] = {
    // ∙█████∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█████∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0fff, 0xff00, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xff00, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x46 = { image_data_Roboto_M_12_0x46,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x47[22] = {
    // ∙∙████∙∙
    // ∙██∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙███∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙∙█████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00ff, 0xff00, 
    0x0ff0, 0x0ff0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0xfff0, 
    0x0f00, 0x00f0, 
    0x0ff0, 0x00f0, 
    0x00ff, 0xfff0, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x47 = { image_data_Roboto_M_12_0x47,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x48[33] = {
    // ∙█∙∙∙∙██∙
    // ∙█∙∙∙∙██∙
    // ∙█∙∙∙∙██∙
    // ∙█∙∙∙∙██∙
    // ∙███████∙
    // ∙█∙∙∙∙██∙
    // ∙█∙∙∙∙██∙
    // ∙█∙∙∙∙██∙
    // ∙█∙∙∙∙██∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x0f00, 0x00ff, 0x0000, 
    0x0f00, 0x00ff, 0x0000, 
    0x0f00, 0x00ff, 0x0000, 
    0x0f00, 0x00ff, 0x0000, 
    0x0fff, 0xffff, 0x0000, 
    0x0f00, 0x00ff, 0x0000, 
    0x0f00, 0x00ff, 0x0000, 
    0x0f00, 0x00ff, 0x0000, 
    0x0f00, 0x00ff, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Roboto_M_12_0x48 = { image_data_Roboto_M_12_0x48,
    9, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x49[11] = {
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x49 = { image_data_Roboto_M_12_0x49,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x4a[22] = {
    // ∙∙∙∙██∙
    // ∙∙∙∙██∙
    // ∙∙∙∙██∙
    // ∙∙∙∙██∙
    // ∙∙∙∙██∙
    // ∙∙∙∙██∙
    // ██∙∙██∙
    // ∙█∙∙██∙
    // ∙████∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0xff00, 
    0x0000, 0xff00, 
    0x0000, 0xff00, 
    0x0000, 0xff00, 
    0x0000, 0xff00, 
    0x0000, 0xff00, 
    0xff00, 0xff00, 
    0x0f00, 0xff00, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x4a = { image_data_Roboto_M_12_0x4a,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x4b[22] = {
    // ∙█∙∙∙██∙
    // ∙█∙∙██∙∙
    // ∙█∙∙█∙∙∙
    // ∙█∙██∙∙∙
    // ∙████∙∙∙
    // ∙██∙█∙∙∙
    // ∙█∙∙██∙∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0f00, 0x0ff0, 
    0x0f00, 0xff00, 
    0x0f00, 0xf000, 
    0x0f0f, 0xf000, 
    0x0fff, 0xf000, 
    0x0ff0, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x00f0, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x4b = { image_data_Roboto_M_12_0x4b,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x4c[22] = {
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█████
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x4c = { image_data_Roboto_M_12_0x4c,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x4d[33] = {
    // ∙██∙∙∙∙∙██∙
    // ∙██∙∙∙∙███∙
    // ∙███∙∙∙███∙
    // ∙█∙█∙∙████∙
    // ∙█∙█∙∙█∙██∙
    // ∙█∙██∙█∙██∙
    // ∙█∙∙███∙██∙
    // ∙█∙∙██∙∙██∙
    // ∙█∙∙∙█∙∙██∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x0ff0, 0x0000, 0xff00, 
    0x0ff0, 0x000f, 0xff00, 
    0x0fff, 0x000f, 0xff00, 
    0x0f0f, 0x00ff, 0xff00, 
    0x0f0f, 0x00f0, 0xff00, 
    0x0f0f, 0xf0f0, 0xff00, 
    0x0f00, 0xfff0, 0xff00, 
    0x0f00, 0xff00, 0xff00, 
    0x0f00, 0x0f00, 0xff00, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Roboto_M_12_0x4d = { image_data_Roboto_M_12_0x4d,
    11, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x4e[33] = {
    // ∙██∙∙∙██∙
    // ∙██∙∙∙██∙
    // ∙███∙∙██∙
    // ∙█∙█∙∙██∙
    // ∙█∙∙█∙██∙
    // ∙█∙∙████∙
    // ∙█∙∙∙███∙
    // ∙█∙∙∙███∙
    // ∙█∙∙∙∙██∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x0ff0, 0x00ff, 0x0000, 
    0x0ff0, 0x00ff, 0x0000, 
    0x0fff, 0x00ff, 0x0000, 
    0x0f0f, 0x00ff, 0x0000, 
    0x0f00, 0xf0ff, 0x0000, 
    0x0f00, 0xffff, 0x0000, 
    0x0f00, 0x0fff, 0x0000, 
    0x0f00, 0x0fff, 0x0000, 
    0x0f00, 0x00ff, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Roboto_M_12_0x4e = { image_data_Roboto_M_12_0x4e,
    9, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x4f[22] = {
    // ∙∙████∙∙
    // ∙██∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙██
    // ∙█∙∙∙∙██
    // ∙█∙∙∙∙██
    // ∙█∙∙∙∙█∙
    // ∙██∙∙██∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00ff, 0xff00, 
    0x0ff0, 0x0ff0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00ff, 
    0x0f00, 0x00ff, 
    0x0f00, 0x00ff, 
    0x0f00, 0x00f0, 
    0x0ff0, 0x0ff0, 
    0x00ff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x4f = { image_data_Roboto_M_12_0x4f,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x50[22] = {
    // ∙█████∙∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙█████∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0fff, 0xff00, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x0ff0, 
    0x0fff, 0xff00, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x50 = { image_data_Roboto_M_12_0x50,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x51[22] = {
    // ∙∙████∙∙
    // ∙██∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙██
    // ∙█∙∙∙∙██
    // ∙█∙∙∙∙██
    // ∙█∙∙∙∙█∙
    // ∙██∙∙██∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    0x00ff, 0xff00, 
    0x0ff0, 0x0ff0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00ff, 
    0x0f00, 0x00ff, 
    0x0f00, 0x00ff, 
    0x0f00, 0x00f0, 
    0x0ff0, 0x0ff0, 
    0x00ff, 0xff00, 
    0x0000, 0x00f0, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x51 = { image_data_Roboto_M_12_0x51,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x52[22] = {
    // ∙█████∙∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙██∙
    // ∙█████∙∙
    // ∙█∙∙██∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙██∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0fff, 0xff00, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x0ff0, 
    0x0f00, 0x0ff0, 
    0x0fff, 0xff00, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0ff0, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x52 = { image_data_Roboto_M_12_0x52,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x53[22] = {
    // ∙∙████∙
    // ∙██∙∙█∙
    // ∙█∙∙∙██
    // ∙██∙∙∙∙
    // ∙∙████∙
    // ∙∙∙∙∙██
    // ██∙∙∙██
    // ∙██∙∙██
    // ∙∙████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00ff, 0xff00, 
    0x0ff0, 0x0f00, 
    0x0f00, 0x0ff0, 
    0x0ff0, 0x0000, 
    0x00ff, 0xff00, 
    0x0000, 0x0ff0, 
    0xff00, 0x0ff0, 
    0x0ff0, 0x0ff0, 
    0x00ff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x53 = { image_data_Roboto_M_12_0x53,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x54[22] = {
    // ███████
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0xffff, 0xfff0, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x54 = { image_data_Roboto_M_12_0x54,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x55[22] = {
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙██∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0ff0, 0x0ff0, 
    0x00ff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x55 = { image_data_Roboto_M_12_0x55,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x56[22] = {
    // ██∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙██∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙██∙∙
    // ∙∙███∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0xff00, 0x00f0, 
    0x0f00, 0x00f0, 
    0x0f00, 0x0ff0, 
    0x0ff0, 0x0f00, 
    0x00f0, 0x0f00, 
    0x00f0, 0xff00, 
    0x00ff, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x56 = { image_data_Roboto_M_12_0x56,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x57[33] = {
    // ██∙∙∙█∙∙∙█∙
    // ∙█∙∙██∙∙∙█∙
    // ∙█∙∙███∙██∙
    // ∙█∙∙█∙█∙██∙
    // ∙██∙█∙█∙█∙∙
    // ∙████∙█∙█∙∙
    // ∙∙██∙∙███∙∙
    // ∙∙██∙∙∙██∙∙
    // ∙∙██∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xff00, 0x0f00, 0x0f00, 
    0x0f00, 0xff00, 0x0f00, 
    0x0f00, 0xfff0, 0xff00, 
    0x0f00, 0xf0f0, 0xff00, 
    0x0ff0, 0xf0f0, 0xf000, 
    0x0fff, 0xf0f0, 0xf000, 
    0x00ff, 0x00ff, 0xf000, 
    0x00ff, 0x000f, 0xf000, 
    0x00ff, 0x000f, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Roboto_M_12_0x57 = { image_data_Roboto_M_12_0x57,
    11, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x58[22] = {
    // ∙█∙∙∙██∙
    // ∙██∙∙█∙∙
    // ∙∙█∙██∙∙
    // ∙∙███∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙███∙∙∙
    // ∙∙█∙██∙∙
    // ∙██∙∙█∙∙
    // ∙█∙∙∙██∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0f00, 0x0ff0, 
    0x0ff0, 0x0f00, 
    0x00f0, 0xff00, 
    0x00ff, 0xf000, 
    0x000f, 0xf000, 
    0x00ff, 0xf000, 
    0x00f0, 0xff00, 
    0x0ff0, 0x0f00, 
    0x0f00, 0x0ff0, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x58 = { image_data_Roboto_M_12_0x58,
    8, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x59[22] = {
    // ██∙∙∙██
    // ∙█∙∙∙██
    // ∙██∙██∙
    // ∙∙█∙██∙
    // ∙∙███∙∙
    // ∙∙∙██∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0xff00, 0x0ff0, 
    0x0f00, 0x0ff0, 
    0x0ff0, 0xff00, 
    0x00f0, 0xff00, 
    0x00ff, 0xf000, 
    0x000f, 0xf000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x59 = { image_data_Roboto_M_12_0x59,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x5a[22] = {
    // ███████
    // ∙∙∙∙∙█∙
    // ∙∙∙∙██∙
    // ∙∙∙██∙∙
    // ∙∙∙█∙∙∙
    // ∙∙██∙∙∙
    // ∙██∙∙∙∙
    // ∙█∙∙∙∙∙
    // ███████
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0xffff, 0xfff0, 
    0x0000, 0x0f00, 
    0x0000, 0xff00, 
    0x000f, 0xf000, 
    0x000f, 0x0000, 
    0x00ff, 0x0000, 
    0x0ff0, 0x0000, 
    0x0f00, 0x0000, 
    0xffff, 0xfff0, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x5a = { image_data_Roboto_M_12_0x5a,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x5b[11] = {
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙██
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0ff0
};
static const tImage Roboto_M_12_0x5b = { image_data_Roboto_M_12_0x5b,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x5c[22] = {
    // ██∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙██∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙██∙
    // ∙∙∙█∙
    // ∙∙∙██
    // ∙∙∙██
    // ∙∙∙∙∙
    0xff00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0ff0, 0x0000, 
    0x00f0, 0x0000, 
    0x00f0, 0x0000, 
    0x00ff, 0x0000, 
    0x000f, 0x0000, 
    0x000f, 0xf000, 
    0x000f, 0xf000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x5c = { image_data_Roboto_M_12_0x5c,
    5, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x5d[11] = {
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ██∙
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0xff00
};
static const tImage Roboto_M_12_0x5d = { image_data_Roboto_M_12_0x5d,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x5e[22] = {
    // ∙∙█∙∙
    // ∙███∙
    // ∙█∙█∙
    // ∙█∙██
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00f0, 0x0000, 
    0x0fff, 0x0000, 
    0x0f0f, 0x0000, 
    0x0f0f, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x5e = { image_data_Roboto_M_12_0x5e,
    5, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x5f[22] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █████
    // ∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xffff, 0xf000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x5f = { image_data_Roboto_M_12_0x5f,
    5, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x60[11] = {
    // ∙█∙∙
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0f00, 
    0x0ff0, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x60 = { image_data_Roboto_M_12_0x60,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x61[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙█∙∙██
    // ∙∙∙∙██
    // ∙█████
    // ∙█∙∙██
    // ∙█∙∙██
    // ∙█████
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0xff00, 
    0x0000, 0xff00, 
    0x0fff, 0xff00, 
    0x0f00, 0xff00, 
    0x0f00, 0xff00, 
    0x0fff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x61 = { image_data_Roboto_M_12_0x61,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x62[22] = {
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙████∙∙
    // ∙██∙██∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙██∙██∙
    // ∙████∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0ff0, 0xff00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0ff0, 0xff00, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x62 = { image_data_Roboto_M_12_0x62,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x63[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙███∙
    // ∙█∙∙██
    // ∙█∙∙∙∙
    // ██∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙██
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0000, 
    0xff00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0xff00, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x63 = { image_data_Roboto_M_12_0x63,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x64[22] = {
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙██∙█∙
    // ∙█∙∙██∙
    // ∙█∙∙∙█∙
    // ██∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙∙██∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0x0f00, 
    0x0000, 0x0f00, 
    0x00ff, 0x0f00, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0xff00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0xff00, 
    0x00ff, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x64 = { image_data_Roboto_M_12_0x64,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x65[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙███∙
    // ∙█∙∙██
    // ∙█∙∙∙█
    // ██████
    // ∙█∙∙∙∙
    // ∙██∙∙█
    // ∙∙███∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0xffff, 0xff00, 
    0x0f00, 0x0000, 
    0x0ff0, 0x0f00, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x65 = { image_data_Roboto_M_12_0x65,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x66[11] = {
    // ∙∙██
    // ∙██∙
    // ████
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00ff, 
    0x0ff0, 
    0xffff, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x66 = { image_data_Roboto_M_12_0x66,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x67[22] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙██∙█∙
    // ∙█∙∙██∙
    // ∙█∙∙∙█∙
    // ██∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙∙██∙█∙
    // ∙█∙∙██∙
    // ∙████∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0x0f00, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0xff00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0xff00, 
    0x00ff, 0x0f00, 
    0x0f00, 0xff00, 
    0x0fff, 0xf000
};
static const tImage Roboto_M_12_0x67 = { image_data_Roboto_M_12_0x67,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x68[22] = {
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙████∙∙
    // ∙█∙∙██∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x68 = { image_data_Roboto_M_12_0x68,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x69[11] = {
    // ∙█∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    0x0f00, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x69 = { image_data_Roboto_M_12_0x69,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x6a[11] = {
    // ∙█∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ██∙
    0x0f00, 
    0x0000, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0xff00
};
static const tImage Roboto_M_12_0x6a = { image_data_Roboto_M_12_0x6a,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x6b[22] = {
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙██
    // ∙█∙██∙
    // ∙███∙∙
    // ∙███∙∙
    // ∙█∙██∙
    // ∙█∙∙█∙
    // ∙█∙∙██
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0f00, 0x0000, 
    0x0f00, 0x0000, 
    0x0f00, 0xff00, 
    0x0f0f, 0xf000, 
    0x0fff, 0x0000, 
    0x0fff, 0x0000, 
    0x0f0f, 0xf000, 
    0x0f00, 0xf000, 
    0x0f00, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x6b = { image_data_Roboto_M_12_0x6b,
    6, 11, 16};
#endif

#if (0x049 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x6c[11] = {
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x6c = { image_data_Roboto_M_12_0x6c,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x6d[33] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙████∙███∙
    // ∙█∙∙██∙∙██
    // ∙█∙∙∙█∙∙██
    // ∙█∙∙∙█∙∙██
    // ∙█∙∙∙█∙∙██
    // ∙█∙∙∙█∙∙██
    // ∙█∙∙∙█∙∙██
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0x0fff, 0xf0ff, 0xf000, 
    0x0f00, 0xff00, 0xff00, 
    0x0f00, 0x0f00, 0xff00, 
    0x0f00, 0x0f00, 0xff00, 
    0x0f00, 0x0f00, 0xff00, 
    0x0f00, 0x0f00, 0xff00, 
    0x0f00, 0x0f00, 0xff00, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Roboto_M_12_0x6d = { image_data_Roboto_M_12_0x6d,
    10, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x6e[22] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙████∙∙
    // ∙█∙∙██∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x6e = { image_data_Roboto_M_12_0x6e,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x6f[22] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙██∙
    // ∙█∙∙∙█∙
    // ██∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0xff00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0xff00, 
    0x00ff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x6f = { image_data_Roboto_M_12_0x6f,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x70[22] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙████∙∙
    // ∙█∙∙██∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙████∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0xff00, 
    0x0fff, 0xf000, 
    0x0f00, 0x0000, 
    0x0f00, 0x0000
};
static const tImage Roboto_M_12_0x70 = { image_data_Roboto_M_12_0x70,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x71[22] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙██∙█∙
    // ∙█∙∙██∙
    // ∙█∙∙∙█∙
    // ██∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙∙██∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x00ff, 0x0f00, 
    0x0f00, 0xff00, 
    0x0f00, 0x0f00, 
    0xff00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0xff00, 
    0x00ff, 0x0f00, 
    0x0000, 0x0f00, 
    0x0000, 0x0f00
};
static const tImage Roboto_M_12_0x71 = { image_data_Roboto_M_12_0x71,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x72[11] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙███
    // ∙██∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0000, 
    0x0fff, 
    0x0ff0, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x72 = { image_data_Roboto_M_12_0x72,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x73[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙█∙∙██
    // ∙█∙∙∙∙
    // ∙████∙
    // ∙∙∙∙██
    // ∙█∙∙██
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xf000, 
    0x0f00, 0xff00, 
    0x0f00, 0x0000, 
    0x0fff, 0xf000, 
    0x0000, 0xff00, 
    0x0f00, 0xff00, 
    0x0fff, 0xf000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x73 = { image_data_Roboto_M_12_0x73,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x74[11] = {
    // ∙∙∙∙
    // ∙██∙
    // ████
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙███
    // ∙∙∙∙
    // ∙∙∙∙
    0x0000, 
    0x0ff0, 
    0xffff, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0fff, 
    0x0000, 
    0x0000
};
static const tImage Roboto_M_12_0x74 = { image_data_Roboto_M_12_0x74,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x75[22] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙███∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0x0f00, 
    0x0f00, 0xff00, 
    0x0fff, 0x0f00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x75 = { image_data_Roboto_M_12_0x75,
    7, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x76[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ██∙∙██
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙████∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xff00, 0xff00, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0xf000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x76 = { image_data_Roboto_M_12_0x76,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x77[33] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ██∙∙█∙∙██
    // ∙█∙∙█∙∙█∙
    // ∙█∙█∙█∙█∙
    // ∙█∙█∙█∙█∙
    // ∙███∙███∙
    // ∙∙██∙██∙∙
    // ∙∙█∙∙∙█∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0xff00, 0xf00f, 0xf000, 
    0x0f00, 0xf00f, 0x0000, 
    0x0f0f, 0x0f0f, 0x0000, 
    0x0f0f, 0x0f0f, 0x0000, 
    0x0fff, 0x0fff, 0x0000, 
    0x00ff, 0x0ff0, 0x0000, 
    0x00f0, 0x00f0, 0x0000, 
    0x0000, 0x0000, 0x0000, 
    0x0000, 0x0000, 0x0000
};
static const tImage Roboto_M_12_0x77 = { image_data_Roboto_M_12_0x77,
    9, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x78[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙██
    // ∙████∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙██∙█∙
    // ██∙∙██
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0f00, 0xff00, 
    0x0fff, 0xf000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x0ff0, 0xf000, 
    0xff00, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x78 = { image_data_Roboto_M_12_0x78,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x79[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ██∙∙██
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙████∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙█∙∙∙
    // ∙██∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0xff00, 0xff00, 
    0x0f00, 0xf000, 
    0x0f00, 0xf000, 
    0x0fff, 0xf000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x00ff, 0x0000, 
    0x00f0, 0x0000, 
    0x0ff0, 0x0000
};
static const tImage Roboto_M_12_0x79 = { image_data_Roboto_M_12_0x79,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x7a[22] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█████
    // ∙∙∙∙█∙
    // ∙∙∙█∙∙
    // ∙∙██∙∙
    // ∙∙█∙∙∙
    // ∙█∙∙∙∙
    // ██████
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0xff00, 
    0x0000, 0xf000, 
    0x000f, 0x0000, 
    0x00ff, 0x0000, 
    0x00f0, 0x0000, 
    0x0f00, 0x0000, 
    0xffff, 0xff00, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x7a = { image_data_Roboto_M_12_0x7a,
    6, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x7b[11] = {
    // ∙∙██
    // ∙∙█∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ██∙∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙∙█∙
    // ∙∙██
    0x00ff, 
    0x00f0, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0xff00, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x00f0, 
    0x00ff
};
static const tImage Roboto_M_12_0x7b = { image_data_Roboto_M_12_0x7b,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x7c[11] = {
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00, 
    0x0f00
};
static const tImage Roboto_M_12_0x7c = { image_data_Roboto_M_12_0x7c,
    3, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x7d[11] = {
    // ██∙∙
    // ∙█∙∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙∙██
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙█∙∙
    // ██∙∙
    0xff00, 
    0x0f00, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x00ff, 
    0x0ff0, 
    0x0ff0, 
    0x0ff0, 
    0x0f00, 
    0xff00
};
static const tImage Roboto_M_12_0x7d = { image_data_Roboto_M_12_0x7d,
    4, 11, 16};
#endif

#if (0x0 == 0x0)
static const uint16_t image_data_Roboto_M_12_0x7e[22] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙███∙∙█∙
    // ∙█∙∙███∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0fff, 0x00f0, 
    0x0f00, 0xfff0, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000, 
    0x0000, 0x0000
};
static const tImage Roboto_M_12_0x7e = { image_data_Roboto_M_12_0x7e,
    8, 11, 16};
#endif


static const tChar Roboto_M_12_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Roboto_M_12_0x20},
#else
  // character: ' ' == ''
  {0x20, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &Roboto_M_12_0x21},
#else
  // character: '!' == ''
  {0x21, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &Roboto_M_12_0x22},
#else
  // character: '"' == ''
  {0x22, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &Roboto_M_12_0x23},
#else
  // character: '#' == ''
  {0x23, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &Roboto_M_12_0x24},
#else
  // character: '$' == ''
  {0x24, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Roboto_M_12_0x25},
#else
  // character: '%' == ''
  {0x25, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &Roboto_M_12_0x26},
#else
  // character: '&' == ''
  {0x26, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &Roboto_M_12_0x27},
#else
  // character: ''' == ''
  {0x27, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &Roboto_M_12_0x28},
#else
  // character: '(' == ''
  {0x28, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &Roboto_M_12_0x29},
#else
  // character: ')' == ''
  {0x29, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &Roboto_M_12_0x2a},
#else
  // character: '*' == ''
  {0x2a, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &Roboto_M_12_0x2b},
#else
  // character: '+' == ''
  {0x2b, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Roboto_M_12_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Roboto_M_12_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Roboto_M_12_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &Roboto_M_12_0x2f},
#else
  // character: '/' == ''
  {0x2f, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Roboto_M_12_0x30},
#else
  // character: '0' == ''
  {0x30, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Roboto_M_12_0x31},
#else
  // character: '1' == ''
  {0x31, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Roboto_M_12_0x32},
#else
  // character: '2' == ''
  {0x32, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Roboto_M_12_0x33},
#else
  // character: '3' == ''
  {0x33, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Roboto_M_12_0x34},
#else
  // character: '4' == ''
  {0x34, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Roboto_M_12_0x35},
#else
  // character: '5' == ''
  {0x35, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Roboto_M_12_0x36},
#else
  // character: '6' == ''
  {0x36, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Roboto_M_12_0x37},
#else
  // character: '7' == ''
  {0x37, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Roboto_M_12_0x38},
#else
  // character: '8' == ''
  {0x38, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Roboto_M_12_0x39},
#else
  // character: '9' == ''
  {0x39, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Roboto_M_12_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &Roboto_M_12_0x3b},
#else
  // character: ';' == ''
  {0x3b, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &Roboto_M_12_0x3c},
#else
  // character: '<' == ''
  {0x3c, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &Roboto_M_12_0x3d},
#else
  // character: '=' == ''
  {0x3d, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &Roboto_M_12_0x3e},
#else
  // character: '>' == ''
  {0x3e, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &Roboto_M_12_0x3f},
#else
  // character: '?' == ''
  {0x3f, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &Roboto_M_12_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Roboto_M_12_0x41},
#else
  // character: 'A' == ''
  {0x41, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Roboto_M_12_0x42},
#else
  // character: 'B' == ''
  {0x42, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Roboto_M_12_0x43},
#else
  // character: 'C' == ''
  {0x43, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Roboto_M_12_0x44},
#else
  // character: 'D' == ''
  {0x44, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Roboto_M_12_0x45},
#else
  // character: 'E' == ''
  {0x45, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Roboto_M_12_0x46},
#else
  // character: 'F' == ''
  {0x46, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Roboto_M_12_0x47},
#else
  // character: 'G' == ''
  {0x47, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Roboto_M_12_0x48},
#else
  // character: 'H' == ''
  {0x48, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &Roboto_M_12_0x49},
#else
  // character: 'I' == ''
  {0x49, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Roboto_M_12_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Roboto_M_12_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Roboto_M_12_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Roboto_M_12_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Roboto_M_12_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &Roboto_M_12_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Roboto_M_12_0x50},
#else
  // character: 'P' == ''
  {0x50, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Roboto_M_12_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Roboto_M_12_0x52},
#else
  // character: 'R' == ''
  {0x52, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Roboto_M_12_0x53},
#else
  // character: 'S' == ''
  {0x53, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Roboto_M_12_0x54},
#else
  // character: 'T' == ''
  {0x54, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Roboto_M_12_0x55},
#else
  // character: 'U' == ''
  {0x55, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Roboto_M_12_0x56},
#else
  // character: 'V' == ''
  {0x56, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Roboto_M_12_0x57},
#else
  // character: 'W' == ''
  {0x57, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Roboto_M_12_0x58},
#else
  // character: 'X' == ''
  {0x58, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Roboto_M_12_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Roboto_M_12_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &Roboto_M_12_0x5b},
#else
  // character: '[' == ''
  {0x5b, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &Roboto_M_12_0x5c},
#else
  // character: '\' == ''
  {0x5c, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &Roboto_M_12_0x5d},
#else
  // character: ']' == ''
  {0x5d, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &Roboto_M_12_0x5e},
#else
  // character: '^' == ''
  {0x5e, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &Roboto_M_12_0x5f},
#else
  // character: '_' == ''
  {0x5f, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &Roboto_M_12_0x60},
#else
  // character: '`' == ''
  {0x60, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Roboto_M_12_0x61},
#else
  // character: 'a' == ''
  {0x61, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &Roboto_M_12_0x62},
#else
  // character: 'b' == ''
  {0x62, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Roboto_M_12_0x63},
#else
  // character: 'c' == ''
  {0x63, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &Roboto_M_12_0x64},
#else
  // character: 'd' == ''
  {0x64, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &Roboto_M_12_0x65},
#else
  // character: 'e' == ''
  {0x65, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &Roboto_M_12_0x66},
#else
  // character: 'f' == ''
  {0x66, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &Roboto_M_12_0x67},
#else
  // character: 'g' == ''
  {0x67, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Roboto_M_12_0x68},
#else
  // character: 'h' == ''
  {0x68, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &Roboto_M_12_0x69},
#else
  // character: 'i' == ''
  {0x69, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &Roboto_M_12_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &Roboto_M_12_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &Roboto_M_12_0x},
#endif

#if (0x049 == 0x0)
  // character: 'l'
  {0x6c, &Roboto_M_12_0x6c},
#else
  // character: 'l' == 'I'
  {0x6c, &Roboto_M_12_0x49},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Roboto_M_12_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &Roboto_M_12_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &Roboto_M_12_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &Roboto_M_12_0x70},
#else
  // character: 'p' == ''
  {0x70, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &Roboto_M_12_0x71},
#else
  // character: 'q' == ''
  {0x71, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &Roboto_M_12_0x72},
#else
  // character: 'r' == ''
  {0x72, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &Roboto_M_12_0x73},
#else
  // character: 's' == ''
  {0x73, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &Roboto_M_12_0x74},
#else
  // character: 't' == ''
  {0x74, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &Roboto_M_12_0x75},
#else
  // character: 'u' == ''
  {0x75, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &Roboto_M_12_0x76},
#else
  // character: 'v' == ''
  {0x76, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &Roboto_M_12_0x77},
#else
  // character: 'w' == ''
  {0x77, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &Roboto_M_12_0x78},
#else
  // character: 'x' == ''
  {0x78, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &Roboto_M_12_0x79},
#else
  // character: 'y' == ''
  {0x79, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &Roboto_M_12_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &Roboto_M_12_0x7b},
#else
  // character: '{' == ''
  {0x7b, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &Roboto_M_12_0x7c},
#else
  // character: '|' == ''
  {0x7c, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &Roboto_M_12_0x7d},
#else
  // character: '}' == ''
  {0x7d, &Roboto_M_12_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &Roboto_M_12_0x7e}
#else
  // character: '~' == ''
  {0x7e, &Roboto_M_12_0x}
#endif

};


const tFont Roboto_M_12 = { 95, Roboto_M_12_array };

